[package]
name = "hasp_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rpassword = "7.0"
arboard = "3.3"

# Link to your local library
hasp_core = { path = "../hasp_core" }